JiaLog/blueprints/admin.py
import os
from flask import Blueprint, render_template, redirect, request, flash, url_for, current_app, send_from_directory
from flask_login import login_required, current_user
from JiaLog.models import Category, Comment, Note
from JiaLog.forms import SettingForm, NoteForm, CategoryForm, CommentForm
from JiaLog.extensions import db
from JiaLog.utils import allowed_file, redirect_back
from flask_ckeditor import upload_fail, upload_success

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.my_title = form.my_title.data
        current_user.my_sub_title = form.my_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('note.index'))
    form.name.data = current_user.name
    form.my_title.data = current_user.my_title
    form.my_sub_title.data = current_user.my_sub_title
    form.about.data = current_user.about
    return render_template('admin/settings.html', form=form)


@admin_bp.route('/note/manage')
@login_required
def manage_note():
    page = request.args.get('page', 1, type=int)
    pagination = Note.query.order_by(Note.timestamp.desc()).paginate(page,
    per_page=current_app.config['JIALOG_MANAGE_POST_PER_PAGE'])
    notes = pagination.items
    return  render_template('admin/manage_note.html', pagination=pagination, notes=notes)


@admin_bp.route('/note/new', methods=['GET', 'POST'])
@login_required
def new_note():
    form = NoteForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        note = Note(title=title, body=body, category=category)
        db.session.add(note)
        db.session.commit()
        flash('Post created.', 'success')
        return redirect(url_for('note.show_note', note_id=note.id))
    return render_template('admin/new_note.html', form=form)


@admin_bp.route('/note/<int:note_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_note(note_id):
    form = NoteForm()
    note = Note.query.get_or_404(note_id)
    if form.validate_on_submit():
        note.title = form.title.data
        note.body = form.body.data
        note.category = Category.query.get(form.category.data)
        db.session.commit()
        flash('note updated', 'success')
        return redirect(url_for('note.show_note', note_id=note.id))
    form.title.data = note.title
    form.body.data = note.body
    form.category.data = note.category_id
    return render_template('admin/edit_note.html', form=form)


@admin_bp.route('/note/<int:note_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_note(note_id):
    note = Note.query.get_or_404(note_id)
    db.session.delete(note)
    db.session.commit()
    flash('note deleted', 'success')
    return redirect_back()


@admin_bp.route('/set-comment/<int:note_id>', methods=['POST'])
@login_required
def set_comment(note_id):
    note = Note.query.get_or_404(note_id)
    if note.can_comment:
        note.can_comment = False
        flash('Comment disabled', 'info')
    else:
        note.can_comment = True
        flash('Comment enabled', 'info')
    db.session.commit()
    return redirect(url_for('note.show_note', note_id=note.id))


@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'success')
    return redirect_back()


@admin_bp.route('/comment/<int:comment_id>/approve', methods=['POST'])
@login_required
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.reviewed = True
    db.session.commit()
    flash('Comment published.', 'success')
    return redirect_back()


@admin_bp.route('/comment/manage', methods=['POST','GET'])
@login_required
def manage_comment():
    filter_rule = request.args.get('filter', 'all')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['JIALOG_COMMENT_PER_PAGE']
    if filter_rule == 'unread':
        filtered_comments = Comment.query.filter_by(reviewed=False)
    elif filter_rule == 'admin':
        filtered_comments = Comment.query.filter_by(from_admin=True)
    else:
        filtered_comments = Comment.query
    pagination = filtered_comments.order_by(Comment.timestamp.desc()).paginate(page, per_page=per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', comments=comments, pagination=pagination)


@admin_bp.route('/category/manage')
@login_required
def manage_category():
    return render_template('admin/manage_category.html')


@admin_bp.route('/category/new', methods=['GET', 'POST'])
@login_required
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        flash('Category created.', 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_category(category_id):
    form = CategoryForm()
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('You can not edit the default category.', 'warning')
        return redirect(url_for('home.index'))
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('Category updated.', 'success')
        return redirect(url_for('.manage_category'))

    form.name.data = category.name
    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('You can not delete the default category.', 'warning')
        return redirect(url_for('home.index'))
    category.delete()
    flash('Category deleted.', 'success')
    return redirect(url_for('.manage_category'))


@admin_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['JIALOG_UPLOAD_PATH'], filename)


@admin_bp.route('/upload', methods=['POST'])
def upload_image():
    f = request.files.get('upload')
    if not allowed_file(f.filename):
        return upload_fail('Image only!')
    f.save(os.path.join(current_app.config['JIALOG_UPLOAD_PATH'], f.filename))
    url = url_for('.get_image', filename=f.filename)
    return upload_success(url, f.filename)

JiaLog/blueprints/note.py
from flask import Blueprint, render_template, request, current_app, url_for, flash, redirect
from JiaLog.models import Category, Note, Comment
from JiaLog.forms import AdminCommentForm, CommentForm
from JiaLog.extensions import db
from flask_login import current_user


note_bp = Blueprint('note', __name__)


@note_bp.route('/', defaults={'page': 1})
@note_bp.route('/page/<int:page>')
def index(page):
    pagination = Note.query.order_by(Note.timestamp.desc()).paginate(page,
                                                                per_page=current_app.config['JIALOG_POST_PER_PAGE'])
    notes = pagination.items
    return render_template('note/index.html',pagination=pagination, notes=notes)


@note_bp.route('/note/<int:note_id>', methods=['GET', 'POST'])
def show_note(note_id):
    note = Note.query.get(note_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['JIALOG_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(note).filter_by(reviewed=True).order_by(Comment.timestamp.asc())\
        .paginate(page, per_page)
    comments = pagination.items
    if current_user.is_authenticated:
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.site.data = url_for('.index')
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = False
    if form.validate_on_submit():
        author = form.author.data
        site = form.site.data
        body = form.body.data
        email = form.email.data
        replied_id = request.args.get('reply')
        comment = Comment(
            author=author, site=site, body=body, from_admin=from_admin, email=email,
            post=note, reviewed=reviewed
        )
        db.session.add(comment)
        db.session.commit()
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
        if current_user.is_authenticated:
            flash('Comment published.', 'success')
        else:
            flash('Thanks, your comment will be published after reviewed', 'info')
        return redirect(url_for('.show_note', note_id=note.id))
    return render_template('note/mynote.html', note=note, pagination=pagination,
                           comments=comments, form=form)


@note_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['JIALOG_POST_PER_PAGE']
    pagination = Note.query.with_parent(category).order_by(Note.timestamp.desc())\
        .paginate(page, per_page=per_page)
    notes = pagination.items
    return render_template('note/category.html', category=category, pagination=pagination, notes=notes)


@note_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(url_for('.show_note', note_id=comment.note_id, reply=comment_id, author=comment.author)+
                    '#comment-form')

JiaLog/templates/note/_notes.html
{% if notes %}
    {% for note in notes %}
        <h3 class="text-primary"><a href="{{ url_for('.show_note', note_id=note.id) }}">{{ note.title }}</a></h3>
        <p>
            {{ note.body|striptags|truncate }}
            <small><a href="{{ url_for('.show_note', note_id=note.id) }}">Read More</a></small>
        </p>
        <small>
            Comments: <a href="{{ url_for('.show_note', note_id=note.id) }}#comments">{{ note.comments|length }}</a>&nbsp;&nbsp;
            Category: <a
                href="{{ url_for('.show_category', category_id=note.category.id) }}">{{ note.category.name }}</a>
            <span class="float-right">{{ moment(note.timestamp).format('LL') }}</span>
        </small>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
    <div class="tip">
        <h5>No notes yet.</h5>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('admin.new_note') }}">Write Now</a>
        {% endif %}
    </div>
{% endif %}

JiaLog/templates/note/_sidebar.html
{% if categories %}
<div class="card mb-3">
    <div class="card-header">Categories</div>
    <ul class="list-group list-group-flush">
        {% for category in categories %}
            <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
            <a href="{{ url_for('note.show_category', category_id = category.id) }}">{{ category.name }}</a>
            <span class="badge badge-primary badge-pill">{{ category.notes|length }}</span>
            </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

JiaLog/templates/note/category.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Category: {{ category.name }}</h1>
        <p class="text-muted">{{ category.notes|length }} posts</p>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include "note/_notes.html" %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <div class="col-sm-4 sidebar">
            {% include "note/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

JiaLog/templates/note/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block content %}
{% if notes %}
    {% for note in notes %}
        <h3 class="text-primary"><a href="{{ url_for('.show_note', note_id=note.id) }}">{{ note.title }}</a></h3>
        <p>
            {{ note.body|striptags|truncate }}
            <small><a href="{{ url_for('.show_note', note_id=note.id) }}">Read More</a></small>
        </p>
        <small>
            Comments: <a href="{{ url_for('.show_note', note_id=note.id) }}#comments">{{ note.comments|length }}</a>&nbsp;&nbsp;
            Category: <a
                href="{{ url_for('.show_category', category_id=note.category.id) }}">{{ note.category.name }}</a>
            <span class="float-right">{{ moment(note.timestamp).format('LL') }}</span>
        </small>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
    <div class="tip">
        <h5>No notes yet.</h5>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('admin.new_note') }}">Write Now</a>
        {% endif %}
    </div>
{% endif %}
{% endblock %}

JiaLog/templates/note/mynote.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'bootstrap/form.html' import render_form %}
{% block title %}{{ note.title }}{% endblock %}
{% block content %}
    <div class="page-header">
    <h1>{{ note.title }}</h1>
    <small>
        Category: <a href="{{ url_for('.show_category', category_id=note.category.id) }}">
        {{note.category.name }}
    </a><br>
        Date: {{ moment(note.timestamp).format('LL') }}
    </small>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {{ note.body|safe }}
        <div class="comments" id="comments">
            <h3>{{ comments|length }} Comments
                <small>
                    <a href="{{ url_for('.show_note', note_id=note.id, page=pagination.pages or 1) }}#comments">
                        latest
                    </a>
                </small>
             {% if current_user.is_authenticated %}
                        <form class="float-right" method="post"
                              action="{{ url_for('admin.set_comment', note_id=note.id, next=request.full_path) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            <button type="submit" class="btn btn-warning btn-sm">
                                {% if note.can_comment %}Disable{% else %}Enable{% endif %} Comment
                            </button>
                        </form>
                    {% endif %}
                {% if comments %}
                    <ul class="list-group">
                        {% for comment in comments %}
                            <li class="list-group-item list-group-item-action flex-column">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">
                                        <a href="{% if comment.site %}{{ comment.site }}
                                            {% else %}#{% endif %}" target="_blank">
                                            {% if comment.from_admin %}{{ admin.name }}
                                            {% else %}
                                                {{ comment.author }}
                                            {% endif %}
                                        </a>
                                    {% if comment.from_admin %}
                                        <span class="badge badge-primary">Author</span>
                                    {% endif %}
                                    {% if comment.replied %}
                                        <span class="badge badge-light">Reply</span>
                                    {% endif %}
                                    </h5>
                                <small data-toggle="tooltip" data-placement="top"
                                       data-delag="500"
                                       data-timestamp="{{ comment.timestamp.strftime('%Y-%dT%H:%M:%SZ') }}">
                                    {{ moment(comment.timestamp).fromNow() }}
                                </small>
                                </div>
                            {% if comment.replied %}
                                <p class="alert alert-dark reply-body">{{ comment.replied.author }}:<br>
                                {{ comment.replied.body }}
                                </p>
                            {% endif %}
                            <p class="mb-1">{{ comment.body }}</p>
                            <div class="float-right">
                                <a class="btn btn-light btn-sm" href="{{ url_for('.reply_comment', comment_id=comment.id) }}">
                                    Reply
                                </a>
                                {% if current_user.is_authenticated %}
                                        <a class="btn btn-light btn-sm" href="mailto:{{ comment.email }}">Email</a>
                                        <form class="inline" method="post"
                                              action="{{ url_for('admin.delete_comment', comment_id=comment.id, next=request.full_path) }}">
                                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                            <button type="submit" class="btn btn-danger btn-sm"
                                                    onclick="return confirm('Are you sure?');">Delete
                                            </button>
                                        </form>
                                    {% endif %}
                            </div>
                            </li>
                    {% endfor %}
                    </ul>
                {% else %}
            <div class="tip"><h5>No comments.</h5></div>
                {% endif %}
            </h3>
        </div>
    {% if comments %}
    {{ render_pagination(pagination, fragment='#comment') }}
    {% endif %}
    {% if request.args.get('reply') %}
        <div class="alert alert-dark">
        Reply to
        <strong>{{ request.args.get('author') }}</strong>:
        <a class="float-right" href="{{ url_for('.show_note', note_id=note.id) }}">Cancel</a>
        </div>
    {% endif %}
     {% if note.can_comment %}
                <div id="comment-form">
                    {{ render_form(form, action=request.full_path) }}
                </div>
            {% else %}
                <div class="tip"><h5>Comment disabled.</h5></div>
            {% endif %}
            </div>
        <div class="col-sm-4 sidebar">
        {% include "note/_sidebar.html" %}
    </div>
    </div>
{% endblock %}