JiaLog/blueprints/admin.py
import os
from flask import Blueprint, render_template, redirect, request, flash, url_for, current_app, send_from_directory
from flask_login import login_required, current_user
from JiaLog.models import Category, Comment, Note
from JiaLog.forms import SettingForm, NoteForm, CategoryForm, CommentForm
from JiaLog.extensions import db
from JiaLog.utils import allowed_file, redirect_back
from flask_ckeditor import upload_fail, upload_success

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.my_title = form.my_title.data
        current_user.my_sub_title = form.my_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('note.index'))
    form.name.data = current_user.name
    form.my_title.data = current_user.my_title
    form.my_sub_title.data = current_user.my_sub_title
    form.about.data = current_user.about
    return render_template('admin/settings.html', form=form)


@admin_bp.route('/note/manage')
@login_required
def manage_note():
    page = request.args.get('page', 1, type=int)
    pagination = Note.query.order_by(Note.timestamp.desc()).paginate(page,
    per_page=current_app.config['JIALOG_MANAGE_POST_PER_PAGE'])
    notes = pagination.items
    return  render_template('admin/manage_note.html', pagination=pagination, notes=notes)


@admin_bp.route('/note/new', methods=['GET', 'POST'])
@login_required
def new_note():
    form = NoteForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        note = Note(title=title, body=body, category=category)
        db.session.add(note)
        db.session.commit()
        flash('Post created.', 'success')
        return redirect(url_for('note.show_note', note_id=note.id))
    return render_template('admin/new_note.html', form=form)


@admin_bp.route('/note/<int:note_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_note(note_id):
    form = NoteForm()
    note = Note.query.get_or_404(note_id)
    if form.validate_on_submit():
        note.title = form.title.data
        note.body = form.body.data
        note.category = Category.query.get(form.category.data)
        db.session.commit()
        flash('note updated', 'success')
        return redirect(url_for('note.show_note', note_id=note.id))
    form.title.data = note.title
    form.body.data = note.body
    form.category.data = note.category_id
    return render_template('admin/edit_note.html', form=form)


@admin_bp.route('/note/<int:note_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_note(note_id):
    note = Note.query.get_or_404(note_id)
    db.session.delete(note)
    db.session.commit()
    flash('note deleted', 'success')
    return redirect_back()


@admin_bp.route('/set-comment/<int:note_id>', methods=['POST'])
@login_required
def set_comment(note_id):
    note = Note.query.get_or_404(note_id)
    if note.can_comment:
        note.can_comment = False
        flash('Comment disabled', 'info')
    else:
        note.can_comment = True
        flash('Comment enabled', 'info')
    db.session.commit()
    return redirect(url_for('note.show_note', note_id=note.id))


@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'success')
    return redirect_back()


@admin_bp.route('/comment/<int:comment_id>/approve', methods=['POST'])
@login_required
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.reviewed = True
    db.session.commit()
    flash('Comment published.', 'success')
    return redirect_back()


@admin_bp.route('/comment/manage', methods=['POST','GET'])
@login_required
def manage_comment():
    filter_rule = request.args.get('filter', 'all')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['JIALOG_COMMENT_PER_PAGE']
    if filter_rule == 'unread':
        filtered_comments = Comment.query.filter_by(reviewed=False)
    elif filter_rule == 'admin':
        filtered_comments = Comment.query.filter_by(from_admin=True)
    else:
        filtered_comments = Comment.query
    pagination = filtered_comments.order_by(Comment.timestamp.desc()).paginate(page, per_page=per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', comments=comments, pagination=pagination)


@admin_bp.route('/category/manage')
@login_required
def manage_category():
    return render_template('admin/manage_category.html')


@admin_bp.route('/category/new', methods=['GET', 'POST'])
@login_required
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        flash('Category created.', 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_category(category_id):
    form = CategoryForm()
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('You can not edit the default category.', 'warning')
        return redirect(url_for('home.index'))
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('Category updated.', 'success')
        return redirect(url_for('.manage_category'))

    form.name.data = category.name
    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('You can not delete the default category.', 'warning')
        return redirect(url_for('home.index'))
    category.delete()
    flash('Category deleted.', 'success')
    return redirect(url_for('.manage_category'))


@admin_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['JIALOG_UPLOAD_PATH'], filename)


@admin_bp.route('/upload', methods=['POST'])
def upload_image():
    f = request.files.get('upload')
    if not allowed_file(f.filename):
        return upload_fail('Image only!')
    f.save(os.path.join(current_app.config['JIALOG_UPLOAD_PATH'], f.filename))
    url = url_for('.get_image', filename=f.filename)
    return upload_success(url, f.filename)

JiaLog/blueprints/auth.py
from flask import Blueprint, redirect, url_for, current_app, flash, render_template
from flask_login import login_user, current_user, logout_user, login_required
from JiaLog.models import Admin
from JiaLog.forms import LoginForm
from JiaLog.utils import redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home.index'))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        admin = Admin.query.first()
        if admin:
            print(username, admin.username)
            if username == admin.username and admin.validate_password(password):
                print(username, admin.username)
                login_user(admin, remember)
                flash('Welcome back.', 'info')
                return redirect_back()
            flash('Invalid username or password.', 'warning')
        else:
            flash('No account.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect_back()

JiaLog/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock title %} - {{ admin.my_title|default('Blog Title') }}</title>
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/%s.min.css' % request.cookies.get('theme', 'superhero')) }}"
              type="text/css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    {% endblock head %}
</head>
<body style="background-color: rgb(7,12,24)">
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('home.index') }}">{{ admin.my_title }}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03"
                    aria-controls="#navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav mr-auto">
                    {{ render_nav_item('home.index', 'Home') }}
                    {{ render_nav_item('home.about', 'About') }}
                    {{ render_nav_item('note.index', 'Notes') }}
                    {{ render_nav_item('home.contact', 'Contact') }}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                New <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.new_note') }}">Note</a>
                                <a class="dropdown-item" href="{{ url_for('admin.new_category') }}">Category</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                Manage <span class="caret"></span>
                                {% if unread_comments %}
                                    <span class="badge badge-success">new</span>
                                {% endif %}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.manage_note') }}">Note</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_category') }}">Category</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_comment') }}">
                                    Comment
                                    {% if unread_comments %}
                                        <span class="badge badge-success">{{ unread_comments }}</span>
                                    {% endif %}
                                </a>
                            </div>
                        </li>
                        {{ render_nav_item('admin.settings', 'Settings') }}
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock nav %}
{% block background %}{% endblock %}
<main class="container" >
    {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ message[0] }}" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message[1] }}
        </div>
    {% endfor %}
    {% block content %}{% endblock content %}
    {% block footer %}
        <footer>
            <p class="float-left">
                <small> &copy; 2021 <a href="#" title="Written by Jia Yaobo">Jia Yaobo</a> -
                    <a href="#" title="Fork me on GitHub">GitHub</a> -
                    <a href="#" title="qq">QQ: 3276422900</a>
                </small>
            </p>
            <p class="float-right">
                <small>
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
                    {% else %}
                        <a href="{{ url_for('auth.login', next=request.full_path) }}">Login</a>
                    {% endif %}
                </small>
            </p>
        </footer>
    {% endblock footer %}
</main>

{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/underscore.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/heart.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/star_animation.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/mouse_rainbow.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
{% endblock %}
</body>
</html>